### ISSUE TITLE
Review report v0.1 analytics

### ISSUE THREAD

**Issue by kristinashu** [mozilla/internet-health-report#33]
Review google analytics for http://internethealthreport.org/

@vojtechmzl and I will meet next week to look at site's metrics and see if there's any info that could influence the design of the new report.

@cadecairos can you please give me access to the analytics?

@samanthaburton @Solanasaurus have you done any previous work that would be relevant? Is there anything in particular you would be curious about?

**Comment by cadecairos** [comment]
@kristinashu you should be able to read the data now

**Comment by kristinashu** [comment]
Got it, thanks!

**Comment by Solanasaurus** [comment]
Hi @kristinashu and @vojtechmzl here is the overview I prepared of the first month of stats, where we saw the bulk of our traffic and engagement, including numbers of comments, annotations, emails, etc. https://docs.google.com/spreadsheets/d/1y5bi5DZV92nRMdFYydgwOstihy-rb3hl4II_gOSDHPc/edit also this blog post on general feedback https://blog.mozilla.org/internetcitizen/2017/05/10/said-mozillas-internet-health-report/

**Comment by Solanasaurus** [comment]
Not sure you if guys worked on this yet, but Kasia and I are eager to hear what you would look at (or what you discover) since we will be preparing materials for Vizzuality soon.

cc @kaodro

**Comment by vojtechsedlak** [comment]
Hi @kristinashu, @kaodro, @Solanasaurus, here is a first [draft](https://docs.google.com/presentation/d/1C3m2RPr-jE6Y7QWMLPhbB7swzdPtDEh_Q1oEuTtZTkQ/edit#slide=id.g16df6e186e_1_0) of the analytics summary. I am still working on the following items, which I hope to add tomorrow. 
- top stories (by language and traffic source)
- user engagement on social media 
- feedback and comments

Please let me know if there are any other pieces you think should be included.

Thanks!

**Comment by Solanasaurus** [comment]
You can't imagine how happy it makes me to see this! Thanks @vojtechmzl - I sent you all the info you need for feedback and comments counts in WP, Hypothes.is, emails and Coral Project.

Let's add PDF downloads. To get the current number we need to ask Chris. It was 58,000 after the first month. Maybe we should include a count of the news media articles too, since there were so many (will look for spreadsheet). I'm surprised more of those articles don't show up higher in the traffic referrals. Perhaps a language breakdown for email subscriptions? (Previously: EN = 1,056 FR = 237 ES = 163 DE = 91)

Below are some of the hypotheses I had after my own analysis that would be great to have your take on. I'm interested in top content by issue or by article or by charts AND especially of repeat visitors since I believe that a lot of people are using the report as a reference guide, returning to it many times. Or reading it over the course of a few visits. I'm interested in anything that can help us understand how people navigated the content and what they found most interesting.
 
- Snippet power is awesome, but we need dedicated landing page to address bounce rate
- Pageviews apart from homepage(s) is much lower
- Time spent on individual pages is high
- Most people only look at a couple of pages
- Chart embeds actually do drive traffic
- Top issues were Privacy (big lead) Decentralization, Open Innovation, Digital Inclusion
- About and Web Literacy trailed the other pages
- Featured stories were significantly popular
- Based on 100k sample around 18,000 people looked at more than 3 pages

**Comment by samanthaburton** [comment]
This is so great to see coming together - thanks a million @vojtechmzl!!

This may be a bit out of scope, but could we also include press hits? The numbers as of Feb 21 are here: https://docs.google.com/spreadsheets/d/1IQcwaXkEuicTAO0AvAom64zh7Wwsnpps2pM2Q2NESX0/edit#gid=0 Maybe @kaodro you could reach out to Justin and/or Kevin to see if we have updated numbers?

**Comment by kaodro** [comment]
Done, I will post here if I get anything new back. Update from Kevin: these are the latest numbers.

**Comment by kristinashu** [comment]
This is fantastic, thank you so much @vojtechmzl!
