### ISSUE TITLE
Stories urls in the v01 do not load content

### ISSUE THREAD

**Issue by kaodro** [mozilla/internet-health-report#37]
Stories in the v01  do not load content  ("Page not found") although they are untouched in wordpress. All language versions are affected. Maybe the stories plugin is broken.

Examples:
[https://internethealthreport.org/v01/stories/people-powered-phones-within-range/](https://internethealthreport.org/v01/stories/people-powered-phones-within-range/)
[https://internethealthreport.org/v01/de/stories/your-selfie-at-the-eiffel-tower/](https://internethealthreport.org/v01/de/stories/your-selfie-at-the-eiffel-tower/)

@cadecairos @kristinashu 

Please fix this as an urgent issue.

**Comment by cadecairos** [comment]
I'm taking a look at this now

**Comment by cadecairos** [comment]
I don't know for sure, but it seems like the Advanced Custom Fields plugin we have installed (4.4.11) isn't working with Wordpress 4.8

I'm going to try upgrading us to ACF 5.x (I'll take a backup of the site first)

**Comment by cadecairos** [comment]
Upgrading the plugin didn't help. I'm talking with WPEngine technical support now, since they're better at PHP+Wordpress than I am.

**Comment by cadecairos** [comment]
@kaodro Looks like they just fixed it. You may need to clear cache and/or test with a private browsing window to see the posts.

**Comment by kaodro** [comment]
Great, it works again, thanks so much for your superquick help!

**Comment by cadecairos** [comment]
For future reference, this happened because an unknown event on the site (maybe a WordPress version update) caused all permalinks to get deleted.

The quick fix, according to WPEngine support is to go to the _Settings->Permalinks_ menu, and toggle the permalink structure to something different, save it, and then switch it back to the original structure. This will cause Wordpress to regenerate all permalinks for posts and custom post types, like Stories and Charts.
